// Generated by the protocol buffer compiler.  DO NOT EDIT!

package  {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class msg_header extends Message {
    public function msg_header() {
      registerField("msgid","",Descriptor.INT32,Descriptor.LABEL_REQUIRED,1);
    }
    // required int32 msgid = 1;
    public var msgid:int = 0;


  }
}