// Generated by the protocol buffer compiler.  DO NOT EDIT!

package  {

  import com.google.protobuf.*;
  import flash.utils.*;
  import com.hurlant.math.BigInteger;
  public final class person_info_c2s extends Message {
    public function person_info_c2s() {
      registerField("msgid","",Descriptor.INT32,Descriptor.LABEL_REQUIRED,1);
      registerField("name","",Descriptor.STRING,Descriptor.LABEL_REQUIRED,2);
      registerField("id","",Descriptor.INT32,Descriptor.LABEL_REQUIRED,3);
    }
    // required int32 msgid = 1;
    public var msgid:int = 0;

    // required string name = 2;
    public var name:String = "";

    // required int32 id = 3;
    public var id:int = 0;


  }
}